spring:
  application:
    name: stock-manager

  # --- Banco de Dados (RDS PostgreSQL) ---
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: StockManagerHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 20000

  # --- Cache e Sessão (ElastiCache Redis) ---
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2000
      timeout: 1000

  # --- Persistência e Hibernate ---
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate # Seguro para produção
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  # --- Migração de Banco (Flyway) ---
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# --- Configurações do Servidor (Tomcat) ---
server:
  port: 8080
  # Essencial para que o Spring reconheça o HTTPS do CloudFront/ALB
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

# --- Monitoramento (Actuator) ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

# --- Logs de Produção ---
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ERROR # Protege dados sensíveis