scrape_configs:
  # Spring Boot
  - job_name: spring-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "stock-manager:8080"

  # Node Exporter
  - job_name: node_exporter
    static_configs:
      - targets:
          - "node-exporter:9100"

  # cAdvisor
  - job_name: cadvisor
    static_configs:
      - targets:
          - "cadvisor:8080"

